import 'package:xml/xml.dart';

import '../styles.dart';
import 'node_to_configurator.dart';
import 'string_ext.dart';

extension StyleToNode on Style {
  /// Converts a Style class into a valid XmlElement that can be used to putted into styles.xml file
  ///
  /// * [relations] is a map that should contains a {id: rId} values (when necessary). This is passed normally by the parser when it generates the styles that are not supported into Word editor, and creates the relations into the document.xml.rels
  XmlElement? toNode({Map<String, String>? relations}) {
    if (id == 'invalid' || styleName == 'invalid' || styleId == 'invalid') return null;
    final XmlElement xmlName = XmlElement.tag(
      'w:name',
      attributes: [
        XmlAttribute('w:val'.toName(), styleName),
      ],
    );
    return XmlElement.tag(
      'w:style',
      attributes: [
        XmlAttribute('w:type'.toName(), type),
        XmlAttribute('w:styleId'.toName(), styleId),
      ],
      children: [
        // if does not have a name into its children, this add it
        if (name == null) xmlName,
        if (!isAutoGenerated)
          XmlElement.tag(
            'w:rsId',
            attributes: <XmlAttribute>[
              XmlAttribute('w:val'.toName(), id),
            ],
          ),
        ...configurators.map(
          (configurator) => configurator.toNode,
        ),
      ],
      isSelfClosing: false,
    );
  }
}
