import '../../../../../docx_transformer.dart';
import '../../../namespaces.dart';

/// Correspond to file docProps/app.xml
//
//TODO: check if this is only generated by default into Word Application
String appDocPropsXmlElement(DocumentProperties docProps, EditorProperties properties) => '''
    <?xml version="1.0" encoding="${docProps.encoding}" standalone="${docProps.standalone}"?>
    <Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
      <Template>${properties.template}</Template>
      <TotalTime>1</TotalTime>
      <Pages>${properties.pages}</Pages>
      <Words>${properties.words}</Words>
      <Characters>${properties.characters}</Characters>
      <Application>Microsoft Office Word</Application>
      <DocSecurity>${properties.docSecurity}</DocSecurity>
      <Lines>${properties.lines}</Lines>
      <Paragraphs>${properties.paragraphs}</Paragraphs>
      <ScaleCrop>false</ScaleCrop>
      <Company></Company>
      <LinksUpToDate>false</LinksUpToDate>
      <CharactersWithSpaces>${properties.charactersWithSpaces}</CharactersWithSpaces>
      <SharedDoc>false</SharedDoc>
      <HyperlinksChanged>false</HyperlinksChanged>
      <AppVersion>${properties.appVersion}</AppVersion>
    </Properties>
''';

/// Correspond to file docProps/core.xml
String generateCoreXml(DocumentProperties properties, EditorProperties editorProps) => '''
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
      <cp:coreProperties
        xmlns:cp="${namespaces['coreProperties']}"
        xmlns:dc="${namespaces['dc']}"
        xmlns:dcterms="${namespaces['dcterms']}"
        xmlns:dcmitype="${namespaces['dcmitype']}"
        xmlns:xsi="${namespaces['xsi']}"
      >
        <dc:title>${properties.title}</dc:title>
        <dc:subject>${properties.subject}</dc:subject>
        <dc:creator>${properties.owner}</dc:creator>
        <cp:keywords>${properties.keywords}</cp:keywords>
        <dc:description>${properties.description}</dc:description>
        <cp:lastModifiedBy>${properties.lastModifiedBy}</cp:lastModifiedBy>
        <cp:revision>${editorProps.numberOfRevisions}</cp:revision>
        <dcterms:createdxsi:type="dcterms:W3CDTF">${properties.createdAt.toUtc()}</dcterms:created>
        <dcterms:modified xsi:type="dcterms:W3CDTF">${properties.modifiedAt.toUtc()}</dcterms:modified>
      </cp:coreProperties>
''';
