name: docx_transformer 
description: "Transform content across popular formats to/from Word documents while preserving formatting, and the richness"
version: 1.0.0
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.2
  dart_quill_delta: ^10.8.3
  flutter_quill_delta_easy_parser: ^1.0.5 
  xml: ^6.5.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
